happybooking_dbt:
  outputs:
    dev:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server'
      server: '7tfceitgb4qeheejfqcx35uvxa-mjuzisw24uuuxdwnidpr22j6l4.datawarehouse.fabric.microsoft.com'
      port: 1433
      database: 'HappyBooking_Warehouse'
      schema: 'gold'
      authentication: 'service_principal'
      tenant_id: '{{ env_var("AZURE_TENANT_ID") }}'
      client_id: '{{ env_var("AZURE_CLIENT_ID") }}'
      client_secret: '{{ env_var("AZURE_CLIENT_SECRET") }}'
  target: dev
